DROP TABLE IF EXISTS ROOM_PASSWORD;
DROP TABLE IF EXISTS PUBLISHED_CHAT_RECORDS;
DROP TABLE IF EXISTS TEACHER_OTHER_LINKS;
DROP TABLE IF EXISTS COMMENTS_VIEWPOINT;
DROP TABLE IF EXISTS COMMENTS_COURSE;
DROP TABLE IF EXISTS ACCESS_RECORDS_VIEWPOINT;
DROP TABLE IF EXISTS ACCESS_RECORDS_COURSE;
DROP TABLE IF EXISTS ACCESS_RECORDS_INFORMATION;
DROP TABLE IF EXISTS INFORMATION_ROOM;
DROP TABLE IF EXISTS CHAT_RECORDS;
DROP TABLE IF EXISTS NEWS_TYPE;
DROP TABLE IF EXISTS NEWS;
DROP TABLE IF EXISTS ROOMS;
DROP TABLE IF EXISTS ROOMS_USERS;
DROP TABLE IF EXISTS LEAVE_WORDS;
DROP TABLE IF EXISTS VIEWPOINTS;
DROP TABLE IF EXISTS COURSES;
DROP TABLE IF EXISTS INFORMATIONS;
DROP TABLE IF EXISTS TEACHERS_PRODUCTS;
DROP TABLE IF EXISTS TEACHERS;
DROP TABLE IF EXISTS USERS_PRODUCTS;
DROP TABLE IF EXISTS USERS;
DROP TABLE IF EXISTS PERSONS;
DROP TABLE IF EXISTS PRODUCTS;

CREATE TABLE PRODUCTS (
  ID INT(10) AUTO_INCREMENT,
  NAME VARCHAR(20) NOT NULL,
  PORTAL VARCHAR(20),
  DESCRIPTION VARCHAR(400),
  CREATE_TIME DATETIME,
  LAST_MODIFIED_TIME DATETIME,
  IS_DELETED BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (ID)
) ENGINE=INNODB CHARSET=utf8;

CREATE TABLE IF NOT EXISTS PERSONS(
  ID INT(10) AUTO_INCREMENT,
  NAME VARCHAR(32) NOT NULL,
  GENDER VARCHAR(10) NOT NULL,
  BIRTHDAY DATE,
  MOBILEPHONE VARCHAR(20) NOT NULL,
  EMAIL VARCHAR(50),
  IDENTITY_CARD VARCHAR(20),
  CREATE_TIME DATETIME,
  LAST_MODIFIED_TIME DATETIME,
  IS_DELETED BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (ID)
) ENGINE=INNODB CHARSET=utf8;

CREATE TABLE USERS (
  ID INT(10) AUTO_INCREMENT,
  LOGGIN_NAME VARCHAR(20) NOT NULL,
  LOGGIN_PASSWORD VARCHAR(40) NOT NULL,
  PERSON INT(10),
  CREATE_TIME DATETIME,
  LAST_MODIFIED_TIME DATETIME,
  IS_DELETED BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (ID),
  FOREIGN KEY FK_USER_PERSON(PERSON) REFERENCES PERSONS(ID)
) ENGINE=INNODB CHARSET=utf8;

CREATE TABLE USERS_PRODUCTS (
  ID INT(10) AUTO_INCREMENT,
  USER INT(10) NOT NULL,
  PRODUCT INT(10) NOT NULL,
  CREATE_TIME DATETIME,
  LAST_MODIFIED_TIME DATETIME,
  PRIMARY KEY (ID),
  FOREIGN KEY FK_USER(USER) REFERENCES USERS(ID),
  FOREIGN KEY FK_PRODUCT(PRODUCT) REFERENCES PRODUCTS(ID)
) ENGINE=INNODB CHARSET=utf8;

CREATE TABLE TEACHERS (
  ID INT(10) AUTO_INCREMENT,
  POSITION VARCHAR(20) NOT NULL,
  CERTIFICATE_NO VARCHAR(20) NOT NULL,
  DESCRIPTION VARCHAR(400) NOT NULL,
  USER INT(10) NOT NULL,
  PHOTO_LOCATION VARCHAR(100),
  CREATE_TIME DATETIME,
  LAST_MODIFIED_TIME DATETIME,
  IS_DELETED BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (ID),
  FOREIGN KEY FK_USER(USER) REFERENCES USERS(ID)
) ENGINE=INNODB CHARSET=utf8;

CREATE TABLE TEACHERS_PRODUCTS (
  ID INT(10) AUTO_INCREMENT,
  TEACHER INT(10) NOT NULL,
  PRODUCT INT(10) NOT NULL,
  CREATE_TIME DATETIME,
  LAST_MODIFIED_TIME DATETIME,
  IS_DELETED BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (ID),
  FOREIGN KEY FK_TEACHER(TEACHER) REFERENCES TEACHERS(ID),
  FOREIGN KEY FK_PRODUCT(PRODUCT) REFERENCES PRODUCTS(ID)
) ENGINE=INNODB CHARSET=utf8;

CREATE TABLE INFORMATIONS (
  ID INT(10) AUTO_INCREMENT,
  TYPE VARCHAR(10) NOT NULL,
  STOCK_CODE VARCHAR(10) NOT NULL,
  STOCK_NAME VARCHAR(20) NOT NULL,
  RELEASE_TIME DATETIME NOT NULL,
  HOLDING_STATUS VARCHAR(10) NOT NULL,
  HOLDING_PERCENT TINYINT NOT NULL,
  PRICE_LOWEST FLOAT(4,2) NOT NULL,
  PRICE_HIGHEST FLOAT(4,2) NOT NULL,
  RECOMMENDATION TEXT NOT NULL,
  OWNER INT(10) NOT NULL,
  CREATE_TIME DATETIME NULL,
  LAST_MODIFIED_TIME DATETIME NULL,
  IS_DELETED BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (ID),
  FOREIGN KEY FK_OWNER(OWNER) REFERENCES TEACHERS(ID)
) ENGINE=INNODB CHARSET=utf8;

CREATE TABLE COURSES (
  ID INT(10) AUTO_INCREMENT,
  TYPE VARCHAR(10) NOT NULL,
  TITLE VARCHAR(40) NOT NULL,
  DESCRIPTION VARCHAR(400) NULL,
  RELEASE_TIME DATETIME NULL,
  IS_CHARGED TINYINT NOT NULL DEFAULT FALSE,
  PRICE DECIMAL(6,2) NULL,
  ACCESSING_PORTAL VARCHAR(200) NULL,
  COVERPAGE_LOCATION VARCHAR(200) NULL,
  OWNER INT(10) NULL,
  CREATE_TIME DATETIME NULL,
  LAST_MODIFIED_TIME DATETIME NULL,
  IS_DELETED BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (ID),
  FOREIGN KEY FK_OWNER(OWNER) REFERENCES TEACHERS(ID)
) ENGINE=INNODB CHARSET=utf8;

CREATE TABLE VIEWPOINTS (
  ID INT(10) AUTO_INCREMENT,
  TITLE VARCHAR(40) NOT NULL,
  CONTENT TEXT NOT NULL,
  RELEASE_TIME DATETIME NULL,
  IS_CHARGED TINYINT NULL DEFAULT FALSE,
  PRICE DECIMAL(6,2) NULL,
  OWNER INT(10) NOT NULL,
  CREATE_TIME DATETIME NULL,
  LAST_MODIFIED_TIME DATETIME NULL,
  IS_DELETED BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (ID),
  FOREIGN KEY FK_OWNER(OWNER) REFERENCES TEACHERS(ID)
) ENGINE=INNODB CHARSET=utf8;

CREATE TABLE LEAVE_WORDS (
  ID INT(10) AUTO_INCREMENT,
  CONTENT VARCHAR(255) NOT NULL,
  WORD_LEAVER VARCHAR(20) NULL,
  MOBILE_PHONE VARCHAR(20) NOT NULL,
  IP_ADDRESS VARCHAR(15) NULL,
  CITY VARCHAR(40) NULL,
  CREATE_TIME DATETIME NULL,
  LAST_MODIFIED_TIME DATETIME NULL,
  IS_DELETED BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (ID) 
) ENGINE=INNODB CHARSET=utf8;

CREATE TABLE ROOMS (
  ID INT(10) AUTO_INCREMENT,
  TYPE VARCHAR(20) NOT NULL,
  OWNER INT(10) NOT NULL,
  MODE VARCHAR(20) NOT NULL,
  DESCRIPTION VARCHAR(200) NULL,
  CREATE_TIME DATETIME NULL,
  LAST_MODIFIED_TIME DATETIME NULL,
  IS_DELETED BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (ID),
  FOREIGN KEY FK_OWNER(OWNER) REFERENCES TEACHERS(ID)
) ENGINE=INNODB CHARSET=utf8;

CREATE TABLE ROOMS_USERS (
  ID INT(10) AUTO_INCREMENT,
  USER INT(10) NOT NULL,
  ROOM INT(10) NOT NULL,
  CREATE_TIME DATETIME,
  LAST_MODIFIED_TIME DATETIME,
  IS_DELETED BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (ID),
  FOREIGN KEY FK_ROOMS_USERS_USER(USER) REFERENCES USERS(ID),
  FOREIGN KEY FK_ROOMS_USERS_ROOM(ROOM) REFERENCES ROOMS(ID)
) ENGINE=INNODB CHARSET=utf8;

CREATE TABLE NEWS (
  ID INT(10) AUTO_INCREMENT,
  TITLE VARCHAR(40) NOT NULL,
  CONTENT TEXT NOT NULL,
  AUTHOR VARCHAR(40) NULL,
  RELEASE_TIME DATETIME NOT NULL,
  ORIGINAL_SOURCE VARCHAR(255) NULL,
  CREATE_TIME DATETIME NULL,
  LAST_MODIFIED_TIME DATETIME NULL,
  IS_DELETED BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (ID)
) ENGINE=INNODB CHARSET=utf8;

CREATE TABLE NEWS_TYPE(
  ID INT(10) AUTO_INCREMENT,
  NEWS INT(10) NOT NULL,
  TYPE VARCHAR(20) NULL,
  CREATE_TIME DATETIME NULL,
  LAST_MODIFIED_TIME DATETIME NULL,
  IS_DELETED BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (ID),
  FOREIGN KEY FK_NEWS(NEWS) REFERENCES NEWS(ID)
) ENGINE=INNODB CHARSET=utf8;

CREATE TABLE CHAT_RECORDS (
  ID INT(10) AUTO_INCREMENT,
  ROOM INT(10) NOT NULL,
  CHAT_TIME DATETIME NULL,
  CONTENT VARCHAR(255) NOT NULL,
  USER INT(10) NOT NULL,
  IS_TEACHER TINYINT NOT NULL DEFAULT FALSE,
  PRIMARY KEY (ID),
  FOREIGN KEY FK_ROOM(ROOM) REFERENCES ROOMS(ID),
  FOREIGN KEY FK_USER(USER) REFERENCES USERS(ID)
) ENGINE=INNODB CHARSET=utf8;

CREATE TABLE INFORMATION_ROOM (
  ID INT(10) AUTO_INCREMENT,
  ROOM INT(10) NOT NULL,
  INFORMATION INT(10) NOT NULL,
  IS_ENABLED TINYINT NULL DEFAULT TRUE,
  CREATE_TIME DATETIME NULL,
  LAST_MODIFIED_TIME DATETIME NULL,
  IS_DELETED BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (ID),
  FOREIGN KEY FK_ROOM(ROOM) REFERENCES ROOMS(ID),
  FOREIGN KEY FK_INFORMATION(INFORMATION) REFERENCES INFORMATIONS(ID)
) ENGINE=INNODB CHARSET=utf8;

CREATE TABLE ACCESS_RECORDS_INFORMATION (
  ID INT(10) AUTO_INCREMENT,
  USER INT(10) NOT NULL,
  INFORMATION INT(10) NOT NULL,
  ACCESSING_TIME DATETIME NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY FK_USER(USER) REFERENCES USERS(ID),
  FOREIGN KEY FK_INFORMATION(INFORMATION) REFERENCES INFORMATIONS(ID)
) ENGINE=INNODB CHARSET=utf8;

CREATE TABLE ACCESS_RECORDS_COURSE (
  ID INT(10) AUTO_INCREMENT,
  USER INT(10) NOT NULL,
  COURSE INT(10) NOT NULL,
  ACCESSING_TIME DATETIME NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY FK_USER(USER) REFERENCES USERS(ID),
  FOREIGN KEY FK_COURSE(COURSE) REFERENCES COURSES(ID)
);

CREATE TABLE ACCESS_RECORDS_VIEWPOINT (
  ID INT(10) AUTO_INCREMENT,
  USER INT(10) NOT NULL,
  VIEWPOINT INT(10) NOT NULL,
  ACCESSING_TIME DATETIME NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY FK_USER(USER) REFERENCES USERS(ID),
  FOREIGN KEY FK_VIEWPOINT(VIEWPOINT) REFERENCES VIEWPOINTS(ID)
) ENGINE=INNODB CHARSET=utf8;

CREATE TABLE COMMENTS_COURSE (
  ID INT(10) AUTO_INCREMENT,
  USER INT(10) NOT NULL,
  COURSE INT(10) NOT NULL,
  CONTENT VARCHAR(200) NOT NULL,
  ADDED_TIME DATETIME NULL,
  CREATE_TIME DATETIME NULL,
  LAST_MODIFIED_TIME DATETIME NULL,
  IS_DELETED BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (ID),
  FOREIGN KEY FK_USER(USER) REFERENCES USERS(ID),
  FOREIGN KEY FK_COURSE(COURSE) REFERENCES COURSES(ID)
) ENGINE=INNODB CHARSET=utf8;

CREATE TABLE COMMENTS_VIEWPOINT (
  ID INT(10) AUTO_INCREMENT,
  USER INT(10) NOT NULL,
  VIEWPOINT INT(10) NOT NULL,
  CONTENT VARCHAR(200) NOT NULL,
  ADDED_TIME DATETIME NULL,
  CREATE_TIME DATETIME NULL,
  LAST_MODIFIED_TIME DATETIME NULL,
  IS_DELETED BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (ID),
  FOREIGN KEY FK_USER(USER) REFERENCES USERS(ID),
  FOREIGN KEY FK_VIEWPOINT(VIEWPOINT) REFERENCES VIEWPOINTS(ID)
) ENGINE=INNODB CHARSET=utf8;

CREATE TABLE TEACHER_OTHER_LINKS (
  ID INT(10) AUTO_INCREMENT,
  TEACHER INT(10) NOT NULL,
  URL VARCHAR(255) NULL,
  CREATE_TIME DATETIME NULL,
  LAST_MODIFIED_TIME DATETIME NULL,
  IS_DELETED BOOLEAN DEFAULT FALSE,
  PRIMARY KEY (ID),
  FOREIGN KEY FK_TEACHER(TEACHER) REFERENCES TEACHERS(ID)
) ENGINE=INNODB CHARSET=utf8;

CREATE TABLE PUBLISHED_CHAT_RECORDS (
  ID INT(10) AUTO_INCREMENT,
  CHAT_RECORD INT(10) NOT NULL,
  PUBLISHED_TIME DATETIME NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY FK_CHAT_RECORD(CHAT_RECORD) REFERENCES CHAT_RECORDS(ID)
) ENGINE=INNODB CHARSET=utf8;

CREATE TABLE ROOM_PASSWORD (
  ID INT(10) AUTO_INCREMENT,
  ROOM INT(10) NOT NULL,
  ROOM_PASSWORD VARCHAR(20) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY FK_ROOM(ROOM) REFERENCES ROOMS(ID)
) ENGINE=INNODB CHARSET=utf8;
